filetype plugin indent on
packadd! matchit
syntax enable

set autoread
set autoindent
set backspace=indent,eol,start
set backupcopy=yes              " preserves file creation time on macOS
set display=lastline
set expandtab
set fileformats=unix
" set grepprg=git\ grep\ -n\ $*
set hidden
set ignorecase
set laststatus=2
set linebreak
set nrformats-=octal
set scrolloff=2
set shiftwidth=2
set smartcase
set smartindent
set softtabstop=2
set splitright
set ttimeout
set ttimeoutlen=100
set wildmode=longest,list,full  " Zsh-style tab completion

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_preview = 1
let g:netrw_winsize = 30

if executable('sourcekit-lsp')
  au User lsp_setup call lsp#register_server({
    \ 'name': 'sourcekit-lsp',
    \ 'cmd': {server_info->['sourcekit-lsp']},
    \ 'allowlist': ['swift'],
    \ })
endif

command Date r !node -p '(new Date()).toISOString()'
